version: '3.8'
services:
  php-apache-environment:
    container_name: php7.4-apache
    depends_on:
      - mariadb
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./html:/var/www/html/
    ports:
      - 8000:80
  mariadb:
    container_name: mariadb
    image: mariadb
    volumes:
      - ./datadir:/var/lib/mysql
    restart: always
    environment:
      MARIADB_PASSWORD: pw
      MARIADB_ROOT_PASSWORD: pw
      MARIADB_USER: user
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
      - php-apache-environment